### ISSUE TITLE
[Critical Issue] if install this mod, the client-side cannot use teleport button

### ISSUE THREAD

**Issue by CoolLKKPS** [Charlese2/HostFixes#10]
same as topic, u can test this issue in LAN mode, even launch 2 game process in same device

**Comment by CoolLKKPS** [comment]
@Charlese2 i have to mention u, this issue is been a while

**Comment by CoolLKKPS** [comment]
[Error  :  HarmonyX] Error while running static void HostFixes.Patches+HostInitialization::Postfix(Terminal __instance). Error: System.NullReferenceException: Object reference not set to an instance of an object
  at HostFixes.Patches+HostInitialization.Postfix (Terminal __instance) [0x0000b] in <a544a9418668440ab2a7c30f10d141f8>:0
  at (wrapper dynamic-method) Terminal.DMD<Terminal::Awake>(Terminal)

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HostFixes.Plugin+HostFixesServerRecieveRpcs.PressTeleportButtonServerRpc (ShipTeleporter instance, Unity.Netcode.ServerRpcParams serverRpcParams) (at <a544a9418668440ab2a7c30f10d141f8>:0)
(wrapper dynamic-method) ShipTeleporter.DMD<ShipTeleporter::__rpc_handler_389447712>(Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by CoolLKKPS** [comment]
not even get this log:
https://github.com/Charlese2/HostFixes/blob/e8d9e3496d2c5ef8d14998428b6ed1db44ade35d/HostFixes/Plugin.cs#L1047

**Comment by CoolLKKPS** [comment]
i notice some typo issue:
> HostFixes.Plugin+HostFixesServerRecieveRpcs.PressTeleportButtonServerRpc (ShipTeleporter instance, Unity.Netcode.ServerRpcParams serverRpcParams) (at :0)

Recieve?

**Comment by Charlese2** [comment]
> @Charlese2 i have to mention u, this issue already 2 months, since v1.0.4

Still hasn't happened to me. Your install might be broken.

**Comment by CoolLKKPS** [comment]
@Charlese2 nope, still, i can send u my modpack to let u to investigate

**Comment by CoolLKKPS** [comment]
[Default_1710001819582.zip](https://github.com/Charlese2/HostFixes/files/14547167/Default_1710001819582.zip)
but im sure even only this mod, this still happen

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HostFixes.Plugin+HostFixesServerRecieveRpcs.DamagePlayerFromOtherClientServerRpc (System.Int32 damageAmount, UnityEngine.Vector3 hitDirection, System.Int32 playerWhoHit, GameNetcodeStuff.PlayerControllerB instance, Unity.Netcode.ServerRpcParams serverRpcParams) (at <a544a9418668440ab2a7c30f10d141f8>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::__rpc_handler_638895557>(Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

**Comment by CoolLKKPS** [comment]
in fact in online session, everyone telling me that they cannot use teleport, and cannot pickup some items

**Comment by CoolLKKPS** [comment]
@Charlese2 update: only the client don't have this mod can trigger this issue, which mean vanilla client

**Comment by Charlese2** [comment]
What operating system are you using?

**Comment by Charlese2** [comment]
> @Charlese2 update: only the client don't have this mod can trigger this issue, which mean vanilla client

I just tried this, and my vanilla client was still able to press the teleport button.

**Comment by Charlese2** [comment]
> [Error : HarmonyX] Error while running static void HostFixes.Patches+HostInitialization::Postfix(Terminal __instance). Error: System.NullReferenceException: Object reference not set to an instance of an object
at HostFixes.Patches+HostInitialization.Postfix (Terminal __instance) [0x0000b] in :0
at (wrapper dynamic-method) Terminal.DMDTerminal::Awake(Terminal)
```c#
// ((MonoBehaviour)(object)Plugin.Instance).StartCoroutine(Plugin.TerminalAwakeWait(__instance));
 IL_0000: call class HostFixes.Plugin HostFixes.Plugin::get_Instance()
 IL_0005: ldarg.0
 IL_0006: call class [netstandard]System.Collections.IEnumerator HostFixes.Plugin::TerminalAwakeWait(class ['Assembly-CSharp']Terminal)
>IL_000b: callvirt instance class [UnityEngine.CoreModule]UnityEngine.Coroutine [UnityEngine.CoreModule]UnityEngine.MonoBehaviour::StartCoroutine(class [netstandard]System.Collections.IEnumerator)
 IL_0010: pop
// }
 IL_0011: ret
``` 
`HostFixes.Plugin::get_Instance()` is returning null so `IL_000b` is causing `System.NullReferenceException: Object reference not set to an instance of an object`. This will not happen unless something external is setting `Plugin.Instance` to `null`.

**Comment by CoolLKKPS** [comment]
hang on

**Comment by CoolLKKPS** [comment]
Windows 11 64-bits

**Comment by CoolLKKPS** [comment]
and btw my p2p connection is not though the steam relay network, might be the problem?

**Comment by Charlese2** [comment]
I'm gonna do another release to add more debugging to Instance code.

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddPlayerChatMessageClientRpc>(HUDManager,string,int)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddPlayerChatMessageServerRpc>(HUDManager,string,int)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:IL_006A)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:IL_0083)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
HarmonyLib.Traverse.GetValue () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0061)
HostFixes.Plugin+HostFixesServerRecieveRpcs.AddPlayerChatMessageServerRpc (System.String chatMessage, System.Int32 playerId, Unity.Netcode.ServerRpcParams serverRpcParams) (at <a544a9418668440ab2a7c30f10d141f8>:IL_00A8)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::__rpc_handler_2930587515>(Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
HUDManager:DMD<HUDManager::AddPlayerChatMessageServerRpc>(HUDManager, String, Int32)
System.Reflection.MethodBase:Invoke(Object, Object[])
MoreCompany.ReflectionUtils:InvokeMethod(Object, String, Object[]) (at D:/VisualStudioProjects/MoreCompany/MoreCompany/ReflectionUtils.cs:12)
MoreCompany.SendChatToServerPatch:Prefix(HUDManager, String, Int32) (at D:/VisualStudioProjects/MoreCompany/MoreCompany/ChatPatches.cs:32)
HUDManager:DMD<HUDManager::AddTextToChatOnServer>(HUDManager, String, Int32)
MoreCompany.ConnectClientToPlayerObjectPatch:Postfix(PlayerControllerB) (at D:/VisualStudioProjects/MoreCompany/MoreCompany/ChatPatches.cs:74)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::ConnectClientToPlayerObject>(PlayerControllerB)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::Update>(PlayerControllerB)

**Comment by CoolLKKPS** [comment]
uh can u make this function can be fully disabled bc i don't want to encounter this issue when i hosting public lobby

**Comment by CoolLKKPS** [comment]
the last error log is from a modpack

**Comment by Charlese2** [comment]
@CoolLKKPS Try 1.0.9

**Comment by CoolLKKPS** [comment]
ok copy

**Comment by CoolLKKPS** [comment]
@Charlese2 the log

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/Charlese2/HostFixes/files/14548246/LogOutput.log)

**Comment by Charlese2** [comment]
Can you run it again without `LessLogs` and `LogNeuter` just to be sure no logs are getting removed?

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/Charlese2/HostFixes/files/14548313/LogOutput.log)

**Comment by CoolLKKPS** [comment]
@Charlese2

**Comment by Charlese2** [comment]
Are you able to build the project on branch [Instance-debugging](https://github.com/Charlese2/HostFixes/tree/Instance-debugging) branch and test that?

**Comment by CoolLKKPS** [comment]
using AMD FX-8300 currently btw

**Comment by CoolLKKPS** [comment]
@Charlese2 uh need a shard link i can't made dll right now

**Comment by CoolLKKPS** [comment]
im not sure what i doing was right so

**Comment by Charlese2** [comment]
Copy these files from `Lethal Company\Lethal Company_Data\Managed` into a directory named `lib`
![image](https://github.com/Charlese2/HostFixes/assets/1207515/f4109546-3cbe-41ec-b788-4b1ec6d633aa)

**Comment by Charlese2** [comment]
Also. OnDestroy is getting called right as the chainloader is finished. Doesn't happen on my end.

```
[Message:   BepInEx] Chainloader startup complete
[Info   :Host Fixes] OnDestroy called and Instance is the current object.
```

**Comment by CoolLKKPS** [comment]
i actually don't know bc lack of knowledge, idk how does this happen and how to prevent that
but if both client install HostFixes this issue won't happen

**Comment by CoolLKKPS** [comment]
![image](https://github.com/Charlese2/HostFixes/assets/96377775/708f5156-30e2-4f83-b0ca-08b3c4705857)

**Comment by Charlese2** [comment]
Does it work if you set `HideManagerGameObject` to `true` in `BepInEx\config\BepInEx.cfg`

**Comment by CoolLKKPS** [comment]
yes it worked

**Comment by CoolLKKPS** [comment]
[LogOutput.log](https://github.com/Charlese2/HostFixes/files/14548375/LogOutput.log)

**Comment by Charlese2** [comment]
I will work it make it not need that setting.

**Comment by CoolLKKPS** [comment]
thx again, and just let u know ur mod did help me prevent more cheater again, that really important, thx a lot

**Comment by Charlese2** [comment]
nice

**Comment by CoolLKKPS** [comment]
9:35 AM at this moment in my timezone and i didn't sleep in this night, i guess i have to sleep now

**Comment by CoolLKKPS** [comment]
im ready for test, let me know when u pushed the new release

**Comment by Charlese2** [comment]
1.0.10 released

**Comment by CoolLKKPS** [comment]
worked, nice

**Comment by CoolLKKPS** [comment]
btw on top of my screen are showing "Host Fixes", uh that's for debug right?

**Comment by Charlese2** [comment]
oops

**Comment by Charlese2** [comment]
That was from GUI branch, it isn't ready yet. Uploaded it accidentally.

**Comment by CoolLKKPS** [comment]
lol okay, and mod works pretty good right now, no issues happen, will let u know if anything wrong happen
