### ISSUE TITLE
[Issue?] some error log show me that player already in my lobby (previous), and another error log show me the player already removed (current), but i just re-create a lobby

### ISSUE THREAD

**Issue by CoolLKKPS** [Charlese2/HostFixes#12]
_Edited by Charlese2 to remove logs_

**Comment by CoolLKKPS** [comment]
@Charlese2 will delete the log after u see it
Find:
[Error  :Host Fixes] SteamId: (???) Name: (???) is already in the connection list.

**Comment by CoolLKKPS** [comment]
btw in the first time they can't join my lobby (i have LobbyControl_Experimental installed), but after i disable LobbyControl_Experimental, even still have those log but the people can able to join

**Comment by CoolLKKPS** [comment]
copied file will early than non-copied file

**Comment by CoolLKKPS** [comment]
in the non-copied log, i re-create the lobby 2 times, with AntiCheat mod and without AntiCheat mod (made by chuxia)

**Comment by CoolLKKPS** [comment]
in the non-copied log, i re-create the lobby 2 times, with AntiCheat mod and without AntiCheat mod (made by chuxia)

**Comment by Charlese2** [comment]
@CoolLKKPS I have the logs now, So you can delete them.

**Comment by Charlese2** [comment]
I added that error so I would know if I didn't clean out the steam names cache. The cleanup code was not being called when the lobby was closed. That caused my error to be printed. It was just an error for info, so it wouldn't stop anyone from joining.

**Comment by CoolLKKPS** [comment]
thx! (i just wake up at this time \@ .. \@)

**Comment by Charlese2** [comment]
Can you test `1.0.12` to see if the log errors are fixed for you?

**Comment by CoolLKKPS** [comment]
will test in this afternoon (UTC+8)

**Comment by CoolLKKPS** [comment]
ah btw, did u remember the issue ticket i mentioned here before? that's cause by HostFixes mod actually, well..
so, after activated radar, the player list sequence in the monitor will be abnormal, only allow 9 players lobby but can have "player # 7" name in player 12 slot, (online mode, and i have a mod can show the player slot number in monitor) this should not happen no matter name or slot glitch

**Comment by CoolLKKPS** [comment]
i actually confuse, who fix the monitor bug...

**Comment by CoolLKKPS** [comment]
@Charlese2 actually the error log changed like this, but seems still not stop player to join:
[Error  :Host Fixes] (???) already removed from playerSteamNames.

> maybe bc the player attempting to join the lobby, but quit in the half way, idk

**Comment by CoolLKKPS** [comment]
confirmed: this error log will trigger when player leaving or joining, i think that no matter they can join the lobby or not

**Comment by CoolLKKPS** [comment]
this function is pretty buggy

**Comment by Charlese2** [comment]
It won't cause any issues.

**Comment by Charlese2** [comment]
Yes

**Comment by CoolLKKPS** [comment]
nice, thx for the reply
