### ISSUE TITLE
[V56] [Error  : Unity Log] ArgumentException: Undefined target method for patch method static (like every title update this mod always break at the beginning)

### ISSUE THREAD

**Issue by CoolLKKPS** [Charlese2/HostFixes#18]
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> HostFixes.Plugin+ServerRPCMessageHandlers+CarCollisionServerRpc_Transpile::UseServerRpcParams(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0047)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_006A)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_006C)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0095)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0007)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0014)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0006)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_001B)
HostFixes.Plugin.Awake () (at ./Plugin.cs:94)
UnityEngine.GameObject:AddComponent()
HostFixes.Plugin:Awake() (at ./Plugin.cs:76)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by CoolLKKPS** [comment]
@Charlese2

**Comment by Charlese2** [comment]
https://github.com/Charlese2/HostFixes/actions/runs/9721034827

**Comment by Charlese2** [comment]
I'm still doing testing for the open beta.

**Comment by CoolLKKPS** [comment]
@Charlese2 sorry for delay reply, i did test this mod about 5 hrs, no issue now and i did hope u release this version now

**Comment by CoolLKKPS** [comment]
due v56 update this broke again

**Comment by Charlese2** [comment]
Already pushed a commit for v56 on GitHub aea8467636c6c9ecb7141ae9fe97cba42e7da816. If I push it to thunderstore it will break for vanilla clients.
