### ISSUE TITLE
The player is blocked from opening the teleporter through the terminal.

### ISSUE THREAD

**Issue by NakiriFox** [Charlese2/HostFixes#19]

**Comment by Charlese2** [comment]
Which mod allows that so I can take a look at it?

**Comment by NakiriFox** [comment]
https://thunderstore.io/c/lethal-company/p/NavarroTech/MoreTerminalCommands/

And I found that it was caused by me placing the terminal far away from the button, and there is no problem with hostfix :)

**Comment by NakiriFox** [comment]
But i think the players should be allowed to lean their terminals against the doorway and use teleportation commands.

Perhaps there should be a more reasonable default value for 'Limit teleporter button distance'?
