### ISSUE TITLE
Preventing Decor Items spawning in

### ISSUE THREAD

**Issue by adamjroark** [Charlese2/HostFixes#2]
Hello there, 

When attempting to purchase any Ship Decor items from the terminal, the console says something like “Host attempted to used XXX credits”. It eats my credits and spawns nothing.

Upon removing Host Fixes, all decor items purchased from the terminal work without issues!

I’ve only tried when in orbit. Doesn’t matter what day you’re on. Just refuses to spawn any decor items in. 

Thanks for making a very needed mod!

**Comment by Charlese2** [comment]
The host is to be the only one that can't buy the Ship Decor items. Should be a fixed when I upload the next version.

**Comment by Charlese2** [comment]
Fixed in 1.0.3.

**Comment by adamjroark** [comment]
Woooooo!! You’re amazing! Thank you so much!
