### ISSUE TITLE
v60 error log

### ISSUE THREAD

**Issue by NakiriFox** [Charlese2/HostFixes#21]
[08:31:29.8467761] [Error  :Host Fixes] Could not patch Terminal.Start

**Comment by Charlese2** [comment]
This is fine. The issue I was patching in `Terminal.Start` is no longer there. My patch is no longer needed, so I just have to remove it.

I was removing `InitializeItemSalesPercentages` from the start of `Terminal.Start` and v60 removed it.

**Comment by NakiriFox** [comment]
good job
