### ISSUE TITLE
game keep show 0 scrap value result after ship take off

### ISSUE THREAD

**Issue by DigitalIver** [Charlese2/HostFixes#3]
When we finish a moons with some scrap and the result screen keep saying we found 0 scrap and we don't get any exp for that.

**Comment by Charlese2** [comment]
What mods are you using? I just tried to reproduce this, but it showed me the value I collected and game me XP.

**Comment by IverDigital** [comment]
Better exp by Swaggies

**Comment by Charlese2** [comment]
Does it start working when you only disable `HostFixes`?

**Comment by IverDigital** [comment]
hmm my assumption is wrong it still show 0 scrap value after disable host fixes

**Comment by IverDigital** [comment]
probally another mod is causing this incompability
