### ISSUE TITLE
Incompatibility with LethalEscape

### ISSUE THREAD

**Issue by koodikas** [Charlese2/HostFixes#5]
LethalEscape does enemy damage to clients with shovels when the (inside) enemies are outside.
It gets logged as the host did the damage to the client, so it gets prevented. Could you do so the host can damage other players or just a toggle for the whole feature. Would be awesome thanks :)

**Comment by Charlese2** [comment]
Version 1.0.7 should fix it.

**Comment by koodikas** [comment]
Awesome, thanks!
