### ISSUE TITLE
Don't prevent any friendly dmg from other player to host, and many error log

### ISSUE THREAD

**Issue by CoolLKKPS** [Charlese2/HostFixes#6]
i have "Reverse_Grief" mod but u just fully prevent any friendly dmg, idk why u have to do that...
and also ur mod didn't log player dmg, but only many error log, just need a few test and u will know

**Comment by Charlese2** [comment]
Are you sure it isn't showing warnings because the `Reverse_Grief` mod is calling the `DamagePlayerFromOtherClientServerRpc` with an id that isn't the person that got hit?

**Comment by Charlese2** [comment]
Can you post the error in here, when you have the time? No rush.

**Comment by Charlese2** [comment]
I need the error from the logs instead of the console.

**Comment by Charlese2** [comment]
Your error seems to be here
https://github.com/Charlese2/HostFixes/blob/e8646c410e00de2078770b22785bfcbacdc9b278/HostFixes/Plugin.cs#L708C17-L708C25
I can only reproduce it by manually setting Instance to null. Just running normally I don't get the error.

**Comment by Charlese2** [comment]
That is the error preventing friendly damage.
